export const SOCKET_LOADING = 'SOCKET_LOADING'
export const SOCKET_START = 'SOCKET_START'
export const SOCKET_UPDATE = 'SOCKET_UPDATE'
export const SOCKET_MESSAGE_ADD='SOCKET_MESSAGE_ADD'
export const SOCKET_CHAT_ADD='SOCKET_CHAT_ADD'
export const SOCKET_ROOM_CHANGE='SOCKET_ROOM_CHANGE'
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT'
export const SOCKET_FAIL = 'SOCKET_FAIL'

export const SOCKET_FALLOW_ME_UPDATE="SOCKET_FALLOW_ME_UPDATE"
export const SOCKET_MY_FALLOW_UPDATE="SOCKET_MY_FALLOW_UPDATE"
/*
 SOCKET_LOADING,
 SOCKET_UPDATE ,
 SOCKET_DISCONNECT ,
 SOCKET_FAIL 
 */