import {
  CONFIG_LOADING,
  CONFIG_UPDATE,
  CONFIG_FAIL,

} from './Types'

const initialState = {
  isStart:false,
  isLoading: false,
  failData: null,
  dc_title: '',
  dc_logoImage: '/logo-dark.png',
  dc_useLogoImage: false,
  dc_mail: '',
  dc_mailName: '',
  dc_usePoint: false,
  dc_loginPoint: 0,
  dc_defaultFont:'Cafe24Simplehae',
  dc_deleteContentDate: 0,
  dc_userProfileChangeDate: 0,
  dc_joinUserLogDelete: 0,
  dc_hotSearchTextDelete: 0,
  dc_captcha: '',
  dc_reCaptchaKey: '',
  dc_reCaptchaSecretKey: '',
  dc_possibleIp: '*',
  dc_impossibleIp: '',
  dc_analytics: '',
  dc_addMeta: '',
  dc_naverSyndicationKey: '',
  dc_textFilter: '',
  dc_reWriteSec: 0,
  dc_searchLimit: 0,
  dc_imageExtention: [],
  dc_videoExtention: [],
  dc_flashExtention: [],
  dc_fileExtention: [],
  dc_excelExtention: [],
  dc_documentExtention:[],
  dc_userImageWeight:500000,
  dc_userFileWeight:500000,
  dc_userVideoWeight:  5000000 ,
  dc_userExcelWeight: 500000 ,
  dc_userDocumentWeight:500000 ,
  dc_addFont: [],
  dc_fontSizes:['10px', '15px', '18px', '24px', '36px', '48px' , '55px' , '64px' ,'72px'],
  dc_useHomepage: false,
  dc_telephone: false,
  dc_address: false,
  dc_mobile: false,
  dc_about: false,
  dc_useReCommender: false,
  dc_reCommenderAddPoint: 3000,
  dc_reCommenderRegisetAddPoint: 3000,
  dc_RegisterPoint: 3000,
  dc_terms: '',
  dc_privacy: '',
  dc_useCert: false,
  dc_selectCert: '',
  dc_certKey: '',
  dc_certSecretKey: '',
  dc_useMail: false,
  dc_auth_naver: { use: false, publicKey: '', secretKey: '' },
  dc_auth_google: { use: false, publicKey: '', secretKey: '' },
  dc_auth_kakao: { use: false, publicKey: '', secretKey: '' },
  dc_auth_fasebook: { use: false, publicKey: '', secretKey: '' },
  dc_auth_twiter: { use: false, publicKey: '', secretKey: '' },
  dc_auth_fayco: { use: false, publicKey: '', secretKey: '' },
  dc_auth_pass: { use: false, publicKey: '', secretKey: '' },
  dc_social_fallow_1: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_social_fallow_2: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_social_fallow_3: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_social_fallow_4: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_social_fallow_5: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_social_fallow_6: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_social_fallow_7: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_social_fallow_8: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_social_fallow_9: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_social_fallow_10: { sf_use: true, sf_label: '', sf_img: '', sf_path: '' },
  dc_useSms: false,
  dc_smsType: 'sms',
  dc_smsTokenKey: '',
  dc_gradeObject:[
    {grade:0,label:'비회원',isAdmin:false,adminJ:false,boardJ:false,groupJ:false,memberJ:false,menuJ:false,pointJ:false,voteJ:false,popupJ:false,pageJ:false},
    {grade:1,label:'일반회원',isAdmin:false,adminJ:false,boardJ:false,groupJ:false,memberJ:false,menuJ:false,pointJ:false,voteJ:false,popupJ:false,pageJ:false},
    {grade:2,label:'우수회원',isAdmin:false,adminJ:false,boardJ:false,groupJ:false,memberJ:false,menuJ:false,pointJ:false,voteJ:false,popupJ:false,pageJ:false},
    {grade:3,label:'특별회원',isAdmin:false,adminJ:false,boardJ:false,groupJ:false,memberJ:false,menuJ:false,pointJ:false,voteJ:false,popupJ:false,pageJ:false},
    {grade:4,label:'vip',isAdmin:false,adminJ:false,boardJ:false,groupJ:false,memberJ:false,menuJ:false,pointJ:false,voteJ:false,popupJ:false,pageJ:false},
    {grade:5,label:'vvip',isAdmin:false,adminJ:false,boardJ:false,groupJ:false,memberJ:false,menuJ:false,pointJ:false,voteJ:false,popupJ:false,pageJ:false},
    {grade:6,label:'vvvip',isAdmin:false,adminJ:false,boardJ:false,groupJ:false,memberJ:false,menuJ:false,pointJ:false,voteJ:false,popupJ:false,pageJ:false}, 
    {grade:7,label:'게시판관리자',isAdmin:true,adminJ:false,boardJ:true,groupJ:false,memberJ:false,menuJ:false,pointJ:false,voteJ:false,popupJ:false,pageJ:false},
    {grade:8,label:'그룹관리자',isAdmin:true,adminJ:false,boardJ:true,groupJ:true,memberJ:false,menuJ:false,pointJ:false,voteJ:false,popupJ:false,pageJ:false},
    {grade:9,label:'부운영자',isAdmin:true,adminJ:false,boardJ:true,groupJ:true,memberJ:true,menuJ:true,pointJ:true,voteJ:true,popupJ:true,pageJ:true},
    {grade:10,label:'운영자',isAdmin:true,adminJ:true,boardJ:true,groupJ:true,memberJ:true,menuJ:true,pointJ:true,voteJ:true,popupJ:true,pageJ:true}, 
    {grade:9999,label:'최고관리자',isAdmin:true,adminJ:true,boardJ:true,groupJ:true,memberJ:true,menuJ:true,pointJ:true,voteJ:true,popupJ:true,pageJ:true},
  ],
  dc_colorObjectBT:[],
  sc_company_owner: '',
  sc_company_name: '',
  sc_company_saupja_no: '',
  sc_company_tel: '',
  sc_company_fax: '',
  sc_tongsin_no: '',
  sc_company_zip: '',
  sc_company_addr: '',
  sc_company_privacy_admin_name: '',
  sc_company_privacy_admin_email: '',
  sc_delivery_company: '',
  sc_delivery_start_time: 17,
  sc_delivery_price: '',
  sc_delivery_infomation: '',
  sc_delivery_change_infomation: '',

  pc_mp_carousel_time_out: 7000,
  pc_mp_carousel_skin: '',
  pc_mp_product_section_1: {
    use: true,
    order: 1,
    label: '인기',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_mp_product_section_2: {
    use: true,
    order: 2,
    label: '추천',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_mp_product_section_3: {
    use: true,
    order: 4,
    label: '히트',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_mp_product_section_4: {
    use: true,
    order: 5,
    label: '할인',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_mp_product_section_5: {
    use: true,
    order: 3,
    label: '최신',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_mp_product_section_6: {
    use: false,
    order: 1,
    label: '',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_mp_product_section_7: {
    use: false,
    order: 1,
    label: '',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_mp_product_section_8: {
    use: false,
    order: 1,
    label: '',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_mp_product_section_9: {
    use: false,
    order: 1,
    label: '',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_mp_product_section_10: {
    use: false,
    order: 1,
    label: '',
    xs: 2,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 4
  },
  pc_lp_use_infinite_scroll: true,
  pc_dp_imgviewr: { imgviewr_skin: '' },
  pc_dp_costviewr: { title_skin: '', content_skin: '', option_skin: '' },
  pc_dp_useSetProduct: true,
  pc_etc_go_to_top: { use: true, color: '', bg: '', border: '' },
  pc_etc_go_to_next_section: { use: true, color: '', bg: '', border: '' },
  pc_etc_use_kakao_chat: true,
  pc_etc_use_naver_chat: true,
  pc_etc_use_server_chat: true,
  pc_etc_left_side: [
    'auth',
    'cart',
    'qna',
    'myoder',
    'delivery_check',
    'comunity',
    'cscenter',
    'social_fallow',
    'todat_click',
    'payment'
  ],
  pc_etc_right_side: ['auth', 'menu'],
  dc_navgation:[],

  dc_levelUpRule:[],
  dc_expContentWrite:10,
  dc_expContentDelete:-10,
  dc_expCommentWrite:10,
  dc_expCommentDelete:-10,
  dc_expGoodClick:10,
  dc_expGoodCancle:-10,
  dc_expBadClick:-10,
  dc_expBadCancle:10,
  dc_expEventClick:[],//event Value , point

  dc_isGoogle_ad:false,
  dc_google_ad_client:'',

}

const reducer = (state = initialState, action) => {
  
  switch (action.type) {
    case CONFIG_LOADING:
      return {
        ...state,
        isLoading: action.payload,
      }
    case CONFIG_UPDATE:
      return {
        ...state,
        isStart:true,
        ...action.payload
        // dc_navgation: action.payload.dc_navgation,
        // dc_title: action.payload.dc_title,
        // dc_logoImage: action.payload.dc_logoImage,
        // dc_useLogoImage: action.payload.dc_useLogoImage,
        // dc_mail: action.payload.dc_mail,
        // dc_mailName: action.payload.dc_mailName,
        // dc_usePoint: action.payload.dc_usePoint,
        // dc_loginPoint: action.payload.dc_loginPoint,
        // dc_deleteContentDate: action.payload.dc_deleteContentDate,
        // dc_userProfileChangeDate: action.payload.dc_userProfileChangeDat,
        // dc_joinUserLogDelete: action.payload.dc_joinUserLogDelete,
        // dc_hotSearchTextDelete: action.payload.dc_hotSearchTextDelete,
        // dc_captcha: action.payload.dc_captcha,
        // dc_reCaptchaKey: action.payload.dc_reCaptchaKey,
        // dc_reCaptchaSecretKey: action.payload.dc_reCaptchaSecretKey,
        // dc_possibleIp: action.payload.dc_possibleIp,
        // dc_impossibleIp: action.payload.dc_impossibleIp,
        // dc_analytics: action.payload.dc_analytics,
        // dc_addMeta: action.payload.dc_addMeta,
        // dc_naverSyndicationKey: action.payload.dc_naverSyndicationKey,
        // dc_textFilter: action.payload.dc_textFilter,
        // dc_reWriteSec: action.payload.dc_reWriteSec,
        // dc_searchLimit: action.payload.dc_searchLimit,
        // dc_imageExtension: action.payload.dc_imageExtension,
        // dc_videoExtention: action.payload.dc_videoExtention,
        // dc_flashExtention: action.payload.dc_flashExtention,
        // dc_gradeObject: action.payload.dc_gradeObject,
        // dc_fileExtention: action.payload.dc_fileExtention,
        // dc_excelExtention: action.payload.dc_excelExtention,

        // dc_addFont: action.payload.dc_addFont,
        // dc_useHomepage: action.payload.dc_useHomepage,
        // dc_telephone: action.payload.dc_telephone,
        // dc_address: action.payload.dc_address,
        // dc_mobile: action.payload.dc_mobile,
        // dc_about: action.payload.dc_about,
        // dc_useReCommender: action.payload.dc_useReCommender,
        // dc_reCommenderAddPoint: action.payload.dc_reCommenderAddPoint,
        // dc_reCommenderRegisetAddPoint: action.payload.dc_reCommenderRegisetAddPoint,
        // dc_userImageWeight: action.payload.dc_userImageWeight,
        // dc_RegisterPoint: action.payload.dc_RegisterPoint,
        // dc_terms: action.payload.dc_terms,
        // dc_privacy: action.payload.dc_privacy,
        // dc_useCert: action.payload.dc_useCert,
        // dc_selectCert: action.payload.dc_selectCert,
        // dc_certKey: action.payload.dc_certKey,
        // dc_certSecretKey: action.payload.dc_certSecretKey,
        // dc_useMail: action.payload.dc_useMail,
        // dc_auth_naver: action.payload.dc_auth_naver,
        // dc_auth_google: action.payload.dc_auth_google,
        // dc_auth_kakao: action.payload.dc_auth_kakao,
        // dc_auth_fasebook: action.payload.dc_auth_fasebook,
        // dc_auth_twiter: action.payload.dc_auth_twiter,
        // dc_auth_fayco: action.payload.dc_auth_fayco,
        // dc_auth_pass: action.payload.dc_auth_pass,
        // dc_social_fallow_1: action.payload.dc_social_fallow_1,
        // dc_social_fallow_2: action.payload.dc_social_fallow_2,
        // dc_social_fallow_3: action.payload.dc_social_fallow_3,
        // dc_social_fallow_4: action.payload.dc_social_fallow_4,
        // dc_social_fallow_5: action.payload.dc_social_fallow_5,
        // dc_social_fallow_6: action.payload.dc_social_fallow_6,
        // dc_social_fallow_7: action.payload.dc_social_fallow_7,
        // dc_social_fallow_8: action.payload.dc_social_fallow_8,
        // dc_social_fallow_9: action.payload.dc_social_fallow_9,
        // dc_social_fallow_10: action.payload.dc_social_fallow_10,
        // dc_useSms: action.payload.dc_useSms,
        // dc_smsType: action.payload.dc_smsTyp,
        // dc_smsTokenKey: action.payload.dc_smsTokenKey,

        // sc_company_owner: action.payload.sc_company_owner,
        // sc_company_name: action.payload.sc_company_name,
        // sc_company_saupja_no: action.payload.sc_company_saupja_no,
        // sc_company_tel: action.payload.sc_company_tel,
        // sc_company_fax: action.payload.sc_company_fax,
        // sc_tongsin_no: action.payload.sc_tongsin_no,
        // sc_company_zip: action.payload.sc_company_zip,
        // sc_company_addr: action.payload.sc_company_addr,
        // sc_company_privacy_admin_name: action.payload.sc_company_privacy_admin_name,
        // sc_company_privacy_admin_email: action.payload.sc_company_privacy_admin_email,
        // sc_delivery_company: action.payload.sc_delivery_company,
        // sc_delivery_start_time: action.payload.sc_delivery_start_time,
        // sc_delivery_price: action.payload.sc_delivery_price,
        // sc_delivery_infomation: action.payload.sc_delivery_infomation,
        // sc_delivery_change_infomation: action.payload.sc_delivery_change_infomation,

        // pc_mp_carousel_time_out: action.payload.pc_mp_carousel_time_out,
        // pc_mp_carousel_skin: action.payload.pc_mp_carousel_skin,
        // pc_mp_product_section_1: action.payload.pc_mp_product_section_1,
        // pc_mp_product_section_2: action.payload.pc_mp_product_section_2,
        // pc_mp_product_section_3: action.payload.pc_mp_product_section_3,
        // pc_mp_product_section_4: action.payload.pc_mp_product_section_4,
        // pc_mp_product_section_5: action.payload.pc_mp_product_section_5,
        // pc_mp_product_section_6: action.payload.pc_mp_product_section_6,
        // pc_mp_product_section_7: action.payload.pc_mp_product_section_7,
        // pc_mp_product_section_8: action.payload.pc_mp_product_section_,
        // pc_mp_product_section_9: action.payload.pc_mp_product_section_9,
        // pc_mp_product_section_10: action.payload.pc_mp_product_section_10,
        // pc_lp_use_infinite_scroll: action.payload.pc_lp_use_infinite_scroll,
        // pc_dp_imgviewr: action.payload.pc_dp_imgview,
        // pc_dp_costviewr: action.payload.pc_dp_costviewr,
        // pc_dp_useSetProduct: action.payload.pc_dp_useSetProduct,
        // pc_etc_go_to_top: action.payload.pc_etc_go_to_to,
        // pc_etc_go_to_next_section: action.payload.pc_etc_go_to_next_sectio,
        // pc_etc_use_kakao_chat: action.payload.pc_etc_use_kakao_chat,
        // pc_etc_use_naver_chat: action.payload.pc_etc_use_naver_cha,
        // pc_etc_use_server_chat: action.payload.pc_etc_use_server_chat,
        // pc_etc_left_side: action.payload.pc_etc_left_side,
        // pc_etc_right_side: action.payload.pc_etc_right_side,
      }

    case CONFIG_FAIL:
      return {
        ...state,
        failData: action.payload,
      }

    default: return state
  }
}

export default reducer
